/**
 * @license
 * Copyright 2019 The Google Earth Engine Community Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

var CLOUD_SHADOW_BIT_MASK = 1 << 3;
var CLOUD_BIT_MASK = 1 << 5;
var QA_BAND = 'pixel_qa';

/**
 * Masks clouds and shadows in the specified image using relevant bits in the
 * `pixel_qa` band generated by the CFMASK algorithm.
 *
 * Returns the image with the mask applied.
 *
 * @param {!ee.Image} image The image to be masked.
 * @return {!ee.Image}
 */
var maskCloudsAndShadows = function(image) {
  // Named args not supported for single object arg function signatures.
  var qa = image.select(QA_BAND);
  // Both flags should be set to zero, indicating clear conditions.
  var mask = qa.bitwiseAnd(CLOUD_SHADOW_BIT_MASK)
                 .eq(0)
                 .and(qa.bitwiseAnd(CLOUD_BIT_MASK).eq(0));
  return image.updateMask(mask);
};

exports.QA_BAND = QA_BAND;
exports.CLOUD_SHADOW_BIT_MASK = CLOUD_SHADOW_BIT_MASK;
exports.CLOUD_BIT_MASK = CLOUD_BIT_MASK;
exports.maskCloudsAndShadows = maskCloudsAndShadows;
